// <auto-generated />
using System;
using MemoryMCP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoryMCP.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    partial class MemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MemoryMCP.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MergedIntoEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ref")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MergedIntoEntityId");

                    b.HasIndex("Name");

                    b.HasIndex("Ref")
                        .IsUnique()
                        .HasFilter("[Ref] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Name")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("Entities", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.EntityRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NewName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("NewType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PreviousName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("PreviousType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("EntityId");

                    b.ToTable("EntityRevisions", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.EntityRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ToEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.HasIndex("FromEntityId", "RelationType");

                    b.HasIndex("ToEntityId", "RelationType");

                    b.HasIndex("FromEntityId", "ToEntityId", "RelationType");

                    b.ToTable("EntityRelationships", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MemoryFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("Raw")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ref")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("SupersededByMemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesMemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("MemoryFrom");

                    b.HasIndex("Ref")
                        .IsUnique()
                        .HasFilter("[Ref] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("SupersededByMemoryId");

                    b.HasIndex("SupersedesMemoryId");

                    b.ToTable("Memories", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.MemoryRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NewMemoryFrom")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PreviousMemoryFrom")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<int>("RevisionType")
                        .HasColumnType("int");

                    b.Property<string>("SuccessorRaw")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SuccessorMemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("MemoryId");

                    b.ToTable("MemoryRevisions", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.MemoryEntity", b =>
                {
                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemoryId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("MemoryEntities", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.MemoryToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("MemoryId", "TokenId")
                        .IsUnique();

                    b.ToTable("MemoryTokens", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("bit");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeValue")
                        .HasColumnType("datetime2");

                    b.Property<float?>("FloatValue")
                        .HasColumnType("real");

                    b.Property<int?>("IntValue")
                        .HasColumnType("int");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Ref")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SearchValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StringValue")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("SupersededByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Property", "IntValue");

                    b.HasIndex("Property", "SearchValue");

                    b.HasIndex("Property", "StringValue");

                    b.HasIndex("Property", "Type", "SearchValue");

                    b.HasIndex("Ref")
                        .IsUnique()
                        .HasFilter("[Ref] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("SupersededByTokenId");

                    b.HasIndex("SupersedesTokenId");

                    b.ToTable("Tokens", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.TokenRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewProperty")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<float?>("NewConfidence")
                        .HasColumnType("real");

                    b.Property<string>("NewSearchValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("NewSource")
                        .HasColumnType("int");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("NewType")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PreviousProperty")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<float?>("PreviousConfidence")
                        .HasColumnType("real");

                    b.Property<string>("PreviousSearchValue")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("PreviousSource")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousType")
                        .HasColumnType("int");

                    b.Property<int>("RevisionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SuccessorTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("TokenId");

                    b.ToTable("TokenRevisions", (string)null);
                });

            modelBuilder.Entity("MemoryMCP.EntityRelationship", b =>
                {
                    b.HasOne("MemoryMCP.Entity", "FromEntity")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("FromEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MemoryMCP.Memory", "Memory")
                        .WithMany()
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MemoryMCP.Entity", "ToEntity")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("ToEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromEntity");

                    b.Navigation("Memory");

                    b.Navigation("ToEntity");
                });

            modelBuilder.Entity("MemoryMCP.Entity", b =>
                {
                    b.HasOne("MemoryMCP.Entity", "MergedIntoEntity")
                        .WithMany()
                        .HasForeignKey("MergedIntoEntityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MergedIntoEntity");
                });

            modelBuilder.Entity("MemoryMCP.EntityRevision", b =>
                {
                    b.HasOne("MemoryMCP.Entity", "Entity")
                        .WithMany("Revisions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("MemoryMCP.Memory", b =>
                {
                    b.HasOne("MemoryMCP.Memory", "SupersededByMemory")
                        .WithMany()
                        .HasForeignKey("SupersededByMemoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MemoryMCP.Memory", "SupersedesMemory")
                        .WithMany()
                        .HasForeignKey("SupersedesMemoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SupersededByMemory");

                    b.Navigation("SupersedesMemory");
                });

            modelBuilder.Entity("MemoryMCP.MemoryRevision", b =>
                {
                    b.HasOne("MemoryMCP.Memory", "Memory")
                        .WithMany("Revisions")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("MemoryMCP.MemoryEntity", b =>
                {
                    b.HasOne("MemoryMCP.Entity", "Entity")
                        .WithMany("Memories")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryMCP.Memory", "Memory")
                        .WithMany("Entities")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Memory");
                });

            modelBuilder.Entity("MemoryMCP.MemoryToken", b =>
                {
                    b.HasOne("MemoryMCP.Memory", "Memory")
                        .WithMany("Tokens")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryMCP.Token", "Token")
                        .WithMany("Memories")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("MemoryMCP.Token", b =>
                {
                    b.HasOne("MemoryMCP.Token", "SupersededByToken")
                        .WithMany()
                        .HasForeignKey("SupersededByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MemoryMCP.Token", "SupersedesToken")
                        .WithMany()
                        .HasForeignKey("SupersedesTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SupersededByToken");

                    b.Navigation("SupersedesToken");
                });

            modelBuilder.Entity("MemoryMCP.TokenRevision", b =>
                {
                    b.HasOne("MemoryMCP.Token", "Token")
                        .WithMany("Revisions")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("MemoryMCP.Entity", b =>
                {
                    b.Navigation("IncomingRelationships");

                    b.Navigation("Memories");

                    b.Navigation("OutgoingRelationships");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("MemoryMCP.Memory", b =>
                {
                    b.Navigation("Entities");

                    b.Navigation("Revisions");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("MemoryMCP.Token", b =>
                {
                    b.Navigation("Memories");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
